version: "3.7"
services:
  gateway:
    build:
      context: gateway
      dockerfile: docker/development/nginx/Dockerfile
    ports:
      - "80:8080"
      - "8081:8081"
    depends_on:
      - frontend
      - api

  frontend:
    build:
      context: frontend
      dockerfile: docker/development/nginx/Dockerfile
    volumes:
      - ./frontend:/app
    depends_on:
      - frontend-node

  frontend-node:
    build:
      context: frontend
      dockerfile: docker/development/node-cli/Dockerfile
    volumes:
      - ./frontend:/app
    command: npm run start
    tty: true
    environment:
      - WDS_SOCKET_PORT=0

  frontend-node-cli:
    build:
      context: frontend
      dockerfile: docker/development/node-cli/Dockerfile
    volumes:
      - ./frontend:/app

  api:
    build:
      context: api
      dockerfile: docker/development/nginx/Dockerfile
    volumes:
      - ./api:/app
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: api
      dockerfile: docker/development/php-fpm/Dockerfile
    volumes:
      - ./api:/app