version: "3.7"
services:
  gateway:
    build:
      context: gateway
      dockerfile: docker/production/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - api
    restart: always

  frontend:
    build:
      context: frontend
      dockerfile: docker/production/nginx/Dockerfile
    restart: always

  api:
    build:
      context: api
      dockerfile: docker/production/nginx/Dockerfile
    depends_on:
      - api-php-fpm
    restart: always

  api-php-fpm:
    build:
      context: api
      dockerfile: docker/production/php-fpm/Dockerfile
    restart: always

#  certbot:
#    image: certbot/certbot
#    restart: unless-stopped
#    volumes:
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"